### ISSUE TITLE
Attempting to load a game on Windows gives JSONDecodeError

### ISSUE THREAD

**Issue by unicus-erik** [KvaGram/Untitled-the-adventure-game#10]
I previously successfully saved a game, but could not load it. Full text of error message from command line when attempting load:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python3\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Python3\GroupProjectAdventureGame\Game.py", line 80, in loadgame
    ldata = json.load(f)
  File "C:\Python3\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Python3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 163 (char 162)
```
The savefile contents read as follows:
`{"version": [1, 2, 2], "prevplace": "apartment", "place": "middle", "inventory": {"HEADACHE": false}, "name": "Annie Mouse", "apartment:window": true, "malefam": `
I imagine there should be a closing } here.

**Comment by KvaGram** [comment]
The savefile is corrupt. The fault is in savegame function. Retry save in debug, note where the fault happens.

**Comment by unicus-erik** [comment]
Retry result:
```Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python3\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Python3\GroupProjectAdventureGame\Game.py", line 126, in savegame
    json.dump(toSave, f)
  File "C:\Python3\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Python3\lib\json\encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python3\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\Python3\lib\json\encoder.py", line 437, in _iterencode
    o = _default(o)
  File "C:\Python3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'FamPerson' is not JSON serializable

**Comment by KvaGram** [comment]
The fault has been identified as the class FamPerson not being serializable. Working on a fix.
Recreation of bug:

1. Start new game
2. Examine table
3. Examine either or both portraits
4. Save game
5. Load the new save game

A fault should appear when saving the game.

**Comment by KvaGram** [comment]
Fix added in commit (https://github.com/KvaGram/Untitled-the-adventure-game/commit/dd80c13898d51ed1338e6d6e0c35885290273865)
Please reopen issue is the bug somehow persists.
